[package]
name = "perspectives"
version = "0.1.0"
authors = ["Simon Gasse <sgasse@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "^0.23.14"
imageproc = "^0.22.0"
rusttype = "^0.9.2"
wasm-bindgen = "^0.2.78"
console_error_panic_hook = { version = "^0.1.7", optional = true }
js-sys = "^0.3.55"

[dependencies.web-sys]
version = "^0.3.55"
features = [
  'CanvasRenderingContext2d',
  'console',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'HtmlInputElement',
  'HtmlElement',
  'ImageData',
  'MessageEvent',
  'MouseEvent',
  'Node',
  'Window',
] 

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"