name: Build and deploy to GH pages

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

env:
  CARGO_TERM_COLORS: always

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM code
        run: ./build.sh

      - name: List build content
        run: tree

      - name: Deploy to GH pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
