name: CI Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build WASM code
        run: ./build.sh
      - name: Publish a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            www
            LICENSE-APACHE
